name: yeahx4
version: 1.0.0
main: yeahx4.Main
commands:
  plugin:
    description: "info of this plugin"
    aliases: ["플러그인", "플긘"]

  areatrigger:
    description: "set trigger within the given area"
    aliases: ["지역트리거"]