name: yeahx4
version: 0.0.2-alpha
main: yeahx4.Main
commands:
  plugin:
    description: "info of this plugin"
    aliases: []

  areatrigger:
    description: "set trigger within the given area"
    aliases: ["at"]

  gettrigger:
    description: "get trigger by name"
    aliases: ["gt"]

  reloadtrigger:
    description: "reload trigger list"
    aliases: ["rt"]

  claim:
    description: "daily claim"
    aliases: ["보상", "일일보상"]

  money:
    description: "check and send money."
    aliases: ["돈"]

  flea:
    description: "open flea macket"
    aliases: ["플리", "플리마켓"]