name: yeahx4
version: 1.0.1
main: yeahx4.Main
commands:
  plugin:
    description: "info of this plugin"
    aliases: []

  areatrigger:
    description: "set trigger within the given area"
    aliases: []

  gettrigger:
    description: "get trigger by name"
    aliases: []